#!/usr/bin/env python3
from pathlib import Path
import sys

import gen_image
import wrap_app


ROOT = Path(__file__).resolve().parents[1]


def write_boot_text(out, boot_text):
    out.append("static const char boot_text[] =\n")
    if not boot_text:
        out.append('    "";\n\n')
        return
    for line in boot_text.splitlines(True):
        escaped = gen_image.c_escape(line).replace("\r", "\\r").replace("\n", "\\n")
        out.append(f'    "{escaped}"\n')
    out.append("    ;\n\n")


def generated_image_source():
    apps_dir = ROOT / "apps"
    files_dir = ROOT / "files"
    sources = gen_image.app_sources(apps_dir, ROOT / "apps/.xiaoignore")
    files = gen_image.file_sources(files_dir, ROOT / "files/.xiaoignore")
    boot_text = (ROOT / "boot/common/boot.txt").read_text()
    out = []
    out.append("/* generated by tools/sync_sketch.py; edit boot/common/boot.txt or apps/ */\n")
    out.append('#include "xiao.h"\n\n')
    for src in sources:
        name = gen_image.app_name(src, apps_dir)
        out.append(f"int {gen_image.symbol_for(name)}(xiao_env *env);\n")
    out.append("\n")
    write_boot_text(out, boot_text)
    for index, src in enumerate(files):
        data = (ROOT / src).read_bytes()
        out.append(f"static const char file_{index}[] = {{\n    ")
        for i, byte in enumerate(data):
            if i and i % 18 == 0:
                out.append("\n    ")
            out.append(f"{byte}, ")
        out.append("0\n};\n\n")
    out.append("static const xiao_app app_table[] = {\n")
    for src in sources:
        name = gen_image.app_name(src, apps_dir)
        out.append(f'    {{ "{gen_image.c_escape(name)}", {gen_image.symbol_for(name)} }},\n')
    out.append("};\n\n")
    out.append("static const xiao_file file_table[] = {\n")
    for index, src in enumerate(files):
        name = gen_image.file_name(src, files_dir)
        size = len((ROOT / src).read_bytes())
        out.append(f'    {{ "{gen_image.c_escape(name)}", file_{index}, {size} }},\n')
    out.append("};\n\n")
    out.append("const xiao_boot_image xiao_image = {\n")
    out.append("    boot_text,\n")
    out.append("    app_table,\n")
    out.append("    sizeof(app_table) / sizeof(app_table[0]),\n")
    out.append("    file_table,\n")
    out.append("    sizeof(file_table) / sizeof(file_table[0]),\n")
    out.append("};\n")
    return "".join(out), sources


def add_source(out, path):
    rel = path.relative_to(ROOT).as_posix()
    out.append(f'\n#line 1 "{rel}"\n')
    out.append(path.read_text())
    out.append("\n")


def add_app_source(out, src):
    name = gen_image.app_name(src, ROOT / "apps")
    path = ROOT / src
    out.append(f'\n#line 1 "{src}"\n')
    out.append(wrap_app.wrapped_source(path, name))
    out.append("\n")


def sync(sketch_dir):
    sketch = Path(sketch_dir)
    if not sketch.is_absolute():
        sketch = ROOT / sketch
    sketch.mkdir(parents=True, exist_ok=True)

    (sketch / "xiao.h").write_text((ROOT / "include/xiao.h").read_text())

    image_source, app_sources = generated_image_source()
    bridge = []
    bridge.append("/* generated by tools/sync_sketch.py; do not edit directly */\n")
    bridge.append('extern "C" {\n')
    add_source(bridge, ROOT / "kernel/core/xiao_core.c")
    bridge.append('\n#line 1 "generated/sketch_image.c"\n')
    bridge.append(image_source)
    for src in app_sources:
        add_app_source(bridge, src)
    bridge.append("}\n")
    (sketch / "xiao_bridge.cpp").write_text("".join(bridge))

    stale = sketch / "xiao_stubs.cpp"
    if stale.exists():
        stale.unlink()


def main():
    if len(sys.argv) < 2:
        print("usage: tools/sync_sketch.py SKETCH_DIR [SKETCH_DIR...]", file=sys.stderr)
        return 2
    for arg in sys.argv[1:]:
        sync(arg)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
